name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: golang:latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag microservice-catalog-system:$(date +%s)
